### ISSUE TITLE
关于-This application cannot create posts on the chosen forum

### ISSUE THREAD

**Issue by shenbowei** [fooleap/disqus-php-api#1]
您好，我在测试postcomment.php提交评论的时候，出现了如下的返回：

```
{"code":12,"thread":null,"response":"This application cannot create posts on the chosen forum"}
```

在单独测试disqus api对应的`posts/create`时也遇到了同样的问题，请问你有遇到过吗？

**Comment by fooleap** [comment]
你好，这应该是申请的 applications 权限的问题，其 Public Key 并不能使用这个 API。
建议先加载 Disqus 官方的评论框，按 F12 可以看到相关请求所用的 Public Key，使用那个 Public Key 就有 `posts/create` 这个权限。

**Comment by shenbowei** [comment]
恩，google了下，看到有人是这样解决的。不过发现貌似这个api_key貌似是通用的：

```
E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F
```

总感觉这样有些不安全，而且官方api文档里貌似也没提到过，测试了secret和public key都不成功，不知道这是不是disqus的bug

**Comment by fooleap** [comment]
才发现所有评论框的 `api_key` 都一样，官网也有一个 `api_key`，它的权限跟评论框应该是一样的。
安全性应该是可以的，这个 Public Key 只有大多数 GET 请求都可以用，一些隐私字段是获取不了，比如用户信息的 Email 地址，除了访客评论之外的 POST 请求好像都没权限。
而获取 Email 地址及其他 POST 操作的权限，则是通过身份认证，即登录状态的网站管理员身份。可以通过模拟登录获取其 `sessionid`，发起请求时加进 cookie。

**Comment by shenbowei** [comment]
@fooleap 恩恩，我之前用secret_key和access_token可以完成除了匿名post/create的功能，一直卡在匿名评论。看来只能用api_key了。另外，看你getpostcomment的代码，没有发现如果thread不存在创建thread的代码呀，这样貌似会有问题，无法在未创建thread里提交评论。

**Comment by fooleap** [comment]
我也是 Google 后才用那个 `api_key` 的，申请的放一边，不大清楚具体的。
是的，那样遇到还没创建的 thread 会出问题。没有加进 `threads/create` 的代码，我是为了防止不小心创建垃圾 thread。自己懒得去清除，就没加进去。
