### ISSUE TITLE
邮箱验证有点问题，匿名评论一直要审核

### ISSUE THREAD

**Issue by ijglb** [fooleap/disqus-php-api#11]
1、jglb@vip.qq.com 类似这种样式的邮箱会提示“请正确填写邮箱。”，验证不通过

2、我测试匿名评论每次都要审核，DISQUS_APPROVED已经设置为true了，disqus里面的相应设置也是None。
查看postcomment.php找到“父评是已登录用户”那块代码发现貌似对父评论是登录的非匿名用户会改成需要审核，但是我在页面直接评论应该不存在父评论吧？目前我暂时注释掉那几行判断代码后就不需要审核了。

审核的问题是我在哪里设置错了吗？

**Comment by fooleap** [comment]
1. 邮箱验证有误是前端的邮箱正则没写对，改好了。
2. 审核问题是因为前端始终传了 `parent`，只是没父评为空，故后端判断不正确。也改了，现在应该正常。

**Comment by ijglb** [comment]
好的，感谢修复
