### ISSUE TITLE
failed to open stream

### ISSUE THREAD

**Issue by aimuz** [fooleap/disqus-php-api#13]
```
<br />
<b>Warning</b>:  file_get_contents(/tmp/session-aimuz.json): failed to open stream: No such file or directory in <b>/var/www/html/disqus/init.php</b> on line <b>40</b><br />
<br />
<b>Warning</b>:  file_get_contents(/tmp/session-aimuz.json): failed to open stream: No such file or directory in <b>/var/www/html/disqus/init.php</b> on line <b>41</b><br />
<br />
<b>Warning</b>:  Creating default object from empty value in <b>/var/www/html/disqus/getcomments.php</b> on line <b>44</b><br />
{"auth":false,"code":null,"cursor":null,"link":"https:\/\/disqus.com\/home\/discussion\/aimuz\/\/?l=zh","posts":null,"response":[],"thread":null}
```
我用的是 php7 ,构建在docker

**Comment by fooleap** [comment]
这可能是你的 PHP 配置是显示 Warning 。
我刚更新了 `init.php` 文件，忽略显示 Warning，可以覆盖下试试。

**Comment by aimuz** [comment]
认证出错，使用那个邮箱和密码是可以登录进去,然后也改了密码尝试。也不行，是不是需要disqus哪里配置什么呢

**Comment by fooleap** [comment]
Disqus 那边应该没什么问题。还没折腾过 Docker，看起来有可能你的 Docker `/tmp` 目录不存在，或者没写的权限。

**Comment by aimuz** [comment]
那可能是这个问题吧，不过使用了docker 搭建 php,上传文件是可以的，是不是可以说明有读写权限。

**Comment by fooleap** [comment]
嗯，还有另一个原因，你的 PHP 没有配置 CURL 扩展。

**Comment by aimuz** [comment]
我试了下
```
<?php
// 使用 sys_get_temp_dir() 在目录里创建临时文件
$temp_file = tempnam(sys_get_temp_dir(), 'Tux');

echo $temp_file;
?>
```
可以创建文件的，是不是说明有权限，对了我的服务器在墙内。
好像发现问题了，我使用这段代码测试
```
<?php
　　$ch = curl_init(); 
　　//设置选项，包括URL
　　curl_setopt($ch, CURLOPT_URL, "https://baidu.com");
　　curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
　　curl_setopt($ch, CURLOPT_HEADER, 0);
　　//执行并获取HTML文档内容
　　$output = curl_exec($ch);
　　//释放curl句柄
　　curl_close($ch);
　　//打印获得的数据
　　print_r($output);
?>
```



`Parse error: syntax error, unexpected '$ch' (T_VARIABLE) in /var/www/html/disqus/aa.php on line 2`

**Comment by fooleap** [comment]
权限应该没问题，可能是 cURL 的问题，找一下 `php.ini` 文件，看看 `extension=php_curl.dll` 是否被注释了。

**Comment by aimuz** [comment]
经过多个测试，CURL 是有用的。
```
<?php
    //初始化
    $curl = curl_init();
    //设置抓取的url
    curl_setopt($curl, CURLOPT_URL, 'http://www.baidu.com');
    //设置头文件的信息作为数据流输出
    curl_setopt($curl, CURLOPT_HEADER, 1);
    //设置获取的信息以文件流的形式返回，而不是直接输出。
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    //执行命令
    $data = curl_exec($curl);
    //关闭URL请求
    curl_close($curl);
    //显示获得的数据
    print_r($data);
?>
```
然后我把api 部署到了一个虚拟主机里面，也是不行的

**Comment by aimuz** [comment]
会不会是因为服务器在墙内的原因

**Comment by fooleap** [comment]
当服务器在墙内时 `config.php` 的设置项 `GFW_INSIDE ` 设为 `true`。

**Comment by aimuz** [comment]
我设置为true了。 aimuz 前段工程师 邮箱：mr.imuz@gmail.com 在2017年10月17日 21:51，Fooleap Chen 写道： 当服务器在墙内时 config.php 的设置项 GFW_INSIDE 设为 true。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by fooleap** [comment]
@aimuz  我刚用阿里云国内虚机试了一下，确实是连不上的原因，最近网络环境差不少……

**Comment by aimuz** [comment]
那是不是需要部署到墙外主机呢。 aimuz 前段工程师 邮箱：mr.imuz@gmail.com 在2017年10月17日 22:09，Fooleap Chen 写道： @aimuz 我刚用阿里云国内虚机试了一下，确实是连不上的原因，最近网络环境差不少…… — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by fooleap** [comment]
你可以试试，我目前部署在阿里云的香港 VPS 上面，一切正常。
