### ISSUE TITLE
什么情况下会触发评论通知？

### ISSUE THREAD

**Issue by aimuz** [fooleap/disqus-php-api#16]
什么情况下会触发评论通知？就是邮件通知

**Comment by fooleap** [comment]
只有在回复匿名评论者（isAnonymous）的评论时，匿名评论者会收到评论回复通知。

**Comment by aimuz** [comment]
昨天我测试了一下，发现并没有收到邮件通知

**Comment by fooleap** [comment]
那得检查 PHP Mailer 的配置是否正确。

**Comment by aimuz** [comment]
我在DEMO上测试，好像也不会有邮箱通知，匿名回复匿名

**Comment by fooleap** [comment]
我看发件箱确实有发送邮件了，你再看看
![](http://ww1.sinaimg.cn/large/699600a0gy1fl1d0l0ci3j209f08v74d.jpg)

**Comment by aimuz** [comment]
确实收到了，可能是我的配置有问题。
