### ISSUE TITLE
由于 Disqus 没有本页面的相关 Thread，故需先创建 Thread

### ISSUE THREAD

**Issue by helloxz** [fooleap/disqus-php-api#20]
按照说明配置好了，但是提示如下截图是什么问题？
![](https://imgurl.org/upload/1804/8e99699206d8198f.png)

**Comment by fooleap** [comment]
若 Disqus 不存在该页所设置 URL 的 thread，是会提示创建。由于担心自动创建会产生垃圾 thread，所以目前都是手动创建，这方面需要优化。

**Comment by helloxz** [comment]
请问如何手动创建，能详细说明一下吗？我直接点提交的时候出现“You must be authenticated to perform this action”

**Comment by fooleap** [comment]
提示没认证，可能因为你 PHP 的配置没填好，`config.php` 填下。

**Comment by helloxz** [comment]
可以了，谢谢。另外请教下是不是每个页面都要自己手动创建一下thread，感觉这样不是很方便。

**Comment by fooleap** [comment]
若文章数很多才开始使用 Disqus，并采用 mode 3 是挺不不方便的，这方面有待优化。
官方评论框会自动创建，你可以设置 mode 为 1，在本地翻墙并依次打开所有文章。

**Comment by helloxz** [comment]
好的，感谢解答。
