### ISSUE TITLE
gravatar不显示

### ISSUE THREAD

**Issue by jozhn** [fooleap/disqus-php-api#25]
不仅是我的博客，博主你的博客也是不显示gravatar的，我发现是因为gravatar链接后面跟了disqus头像的参数导致跳转到noavatar，这个怎么解决呢？

增加设置只显示gravatar而不是disqus头像可能好一点吧？

**Comment by fooleap** [comment]
Gravatar 不显示，是因为访客邮箱号目前已无法正常获取到，所以显示不了 Gravatar 头像，若这个变化坐实，那只能考虑其他方案了，挺可惜的。
Disqus 不显示 Email 的原因 https://blog.disqus.com/update-on-privacy-and-gdpr-compliance

**Comment by jozhn** [comment]
原来是gdpr啊。。。真可惜

**Comment by jozhn** [comment]
对了，这样回复的邮件通知也就没有了。。。唉~

**Comment by fooleap** [comment]
目前能找到的，只有 Disqus 给博主的邮件通知里面邮箱、IP还保留着=。=
