### ISSUE TITLE
Can't load some threads if the site supports both HTTP and HTTPS

### ISSUE THREAD

**Issue by zhaohuabing** [fooleap/disqus-php-api#26]
The current api and js have problem in the following two scenarios:
* The site supports both HTTP and HTTPS
* The site uses HTTP before, then switch to HTTPS, or vice versa

It turns out that the url is not a good choice as the filter to get the thread, because that url changes in different protocols.(http://.... and https://....)

I suggest using identifier instead.
`-$thread = 'link:'.$website.$_GET['link'];`
`+$thread = 'ident:'.$_GET['ident'];`
The js client need to be modified accordingly too.

If you also agree it's a good solution, I'll send a pull request to fix it.

**Comment by fooleap** [comment]
此前我也是经历过 HTTP 切换到 HTTPS，解决的方法是：
1. 使用 Disqus 后台的 [Migration Tools](https://disqus.com/admin/discussions/migrate/) 中的 Upload a URL map，其简介也提到了协议的切换可用这个工具。
2. 一段时间之后大部分 `thread` 的链接更改生效，没有发生变化的 `thread` 可通过 [Edit Discussions](https://disqus.com/admin/discussions/) 手动编辑。
3. 配置相应改变即可。

因目前无法保证所有人在使用此项目之前，使用 Disqus 评论框，所设置的 `ident` 都按照此项目的规则，所以不大算移除 url 为参获取 `thread` 的方法。

注意到，如果同时传 `link` 和 `ident`，Disqus 会优先返回 `ident` 的数据。或许也可以有更好的解决方案，先以 `ident` 为参数请求，获取不到再以 `link` 为参进行请求。

PS：不好意思英语不擅长，直接中文回复。

**Comment by zhaohuabing** [comment]
如果网站同时支持http和https的话会存在问题。
1、一个客户端通过http访问，创建了一个http url的thread。
2、另一个客户端用https访问，根据url会找不到该thread，创建时由于会按照identifier判重，会提示thread已经存在，创建失败。
此时基于https访问的客户端就无法正常进行评论了。

**Comment by fooleap** [comment]
https://help.disqus.com/developer/what-is-a-disqus-identifier
这篇文章的最后一句提到：所有的 thread 都有 id，但不是所有的 thread 都有 identifier。

https://help.disqus.com/troubleshooting/why-are-the-same-comments-showing-up-on-multiple-pages
而在上面链接可以看到，若使用官方评论框，相同的 url 是会被加载相同 thread id 的评论。

把 http 迁移到 https，只是迁移的过程中会存在问题，一旦迁移完成，问题就不复存在了。

目前域名是在通过设置后端的 `DISQUS_WEBSITE` 确定的，即使网站同时支持 http 和 https，都会以 `DISQUS_WEBSITE` 为准。

**Comment by zhaohuabing** [comment]
明白了，这样应该就没问题了。
