### ISSUE TITLE
建议将暂存的数据存储在数据库中

### ISSUE THREAD

**Issue by poplite** [fooleap/disqus-php-api#27]
disqus-php-api 暂存的数据一般存储在`/tmp`目录里，因此一旦机器重启，所有的数据都丢失了（特别是匿名用户的邮箱地址）。

能否存储在一个 SQL 数据库中，或者`/tmp`目录以外的地方，防止重启后数据丢失？

**Comment by poplite** [comment]
我自己把代码改成存储在 PostgreSQL 数据库中了：https://github.com/poplite/disqus-php-api/commit/a59cdedfc2a5044819ed1297ac3d7d5910e98553 （ PHP7 和 PostgreSQL 10 环境下测试通过 ）

本来是写给自己部署在 Heroku 上的 disqus-php-api 的。Heroku 应用处于不活动状态超过30分钟就强制休眠，数据被清空，只好存储在数据库中了。

**Comment by fooleap** [comment]
刚开始我就没打算存储数据，只做代理。但发现有些权限，还必须得是管理员才能获得，所以存储了 session，量比较小，没考虑数据库简单存下。没想到各种主机对临时文件目录的管理是不同的，没选好。
由于最近 Disqus 不给 Email，所以还得存一段时间的邮箱号。考虑把文件移到当前目录下，可选数据库存储。
