### ISSUE TITLE
提交评论报错

### ISSUE THREAD

**Issue by ariwori** [fooleap/disqus-php-api#29]
![_2018-06-28_21-02-03.png](https://chevereto-1252378140.file.myqcloud.com/images/2018/06/28/_2018-06-28_21-02-03.png)
这是在你的demo页测试的

**Comment by fooleap** [comment]
我俩账号测试都正常，再试一下？

**Comment by ariwori** [comment]
我感觉是我账号的问题，我决定放弃静态博客了，typecho感觉不错=_=
