### ISSUE TITLE
由于 Disqus 没有本页面的相关 Thread，故需先创建 Thread

### ISSUE THREAD

**Issue by hubojing** [fooleap/disqus-php-api#3]
请问这是什么情况？如何解决？谢谢。

**Comment by fooleap** [comment]
一般一个 thread 对应一个网页，若使用官方的评论框代码，thread 会自动创建。
使用 API 的话，手动创建可以减少垃圾 thread 的产生。 
创建 thread 的 API 文档在这 https://disqus.com/api/docs/threads/create/
一般 url 和 title 是必填，其余是选填。

**Comment by hubojing** [comment]
那这样会影响我导入的历史评论吗？

**Comment by fooleap** [comment]
如果你的历史评论对应的页面 url （可以在 Disqus 网站管理 TOOLS > Discussions 查看），和目前网站的页面 url 是一一对应的，那没有问题，每条 thread 对应的 url 似乎是唯一的。

建议先导入历史评论，再使用我这个评论框。

**Comment by hubojing** [comment]
评论后好像无法显示？但API接口似乎加载了评论。Disqus甚至邮件提醒了我。这是怎么回事呢？

**Comment by fooleap** [comment]
看看 Disqus 网站设置会不会开启了评论预审核，把它关掉。

**Comment by racall** [comment]
就是把Pre-moderation设置None?    设置过后还是需要审核

**Comment by racall** [comment]
@fooleap 就是把Pre-moderation设置None? 设置过后还是需要审核呀

**Comment by fooleap** [comment]
@racall 不知道会不会是 Disqus 对不同注册时间的账号做了限制，我开启后除了垃圾评论，都不需要再审核了。
如果还需要审核，建议在评论管理里面将访客的邮箱号加入信任列表。

**Comment by racall** [comment]
@fooleap 这个问题应该不是这个原因吧  我看到有几个使用你这个评论框的   都需要审核   匿名评论不审核显示不出来

**Comment by fooleap** [comment]
@racall 是的，之前有两三个朋友说过，但我看各种设置和我自己的没有区别，暂时找不出是什么原因，只能是有新评论就信任掉，以后就不用再审。

**Comment by racall** [comment]
@fooleap 关于这个问题   可以咨询一下客服试试看看？

**Comment by fooleap** [comment]
@racall 应该可以，或者去 Disqus 开发者讨论区看看。

找时间我再翻一下，是否有其他的设置被我忽略了。

**Comment by fooleap** [comment]
@racall 发现发表评论 API 中有个可选参数（state）可以解决 https://disqus.com/api/docs/posts/create/
已加进去

**Comment by choicky** [comment]
我用目前最新的代码 [做了测试](https://zhoucaiqi.com/2017/07/02/hugo-academic-markdown-latex/)，目前匿名评论者的评论已无需审核。

**Comment by racall** [comment]
@fooleap   测试了一下  可以使用

**Comment by hubojing** [comment]
已能正常使用，非常感谢。
