### ISSUE TITLE
邮件提醒的问题

### ISSUE THREAD

**Issue by AlanDecode** [fooleap/disqus-php-api#31]
你好，请问邮件回复提醒有相关的日志可以查看吗？我这里基本上没有成功过，config.php 中已经对应配置，想知道是不是 VPS 的原因。

**Comment by fooleap** [comment]
刚我修改了发送邮件的部分，开启了 PHPMailer 的调试模式，若发送失败，日志会在 <code>/cache/phpmailer_error.log</code>。

**Comment by AlanDecode** [comment]
好的，谢谢
