### ISSUE TITLE
PHP Mailer 是做什么用的？

### ISSUE THREAD

**Issue by choicky** [fooleap/disqus-php-api#4]
我最初设了相关的信息；

后来没有设，感觉用起来没有区别？

**Comment by fooleap** [comment]
回复邮件通知，正确配置之后：
若在评论框回复匿名评论者，对方会有回复邮件通知。
回复登录用户则没，因 Disqus 自己有邮件通知。

**Comment by choicky** [comment]
用腾讯的免费企业邮 [试了几次](https://zhoucaiqi.com/2017/07/02/hugo-academic-markdown-latex/)，匿名评论者目前没收到邮件。

下面的设置应该是对的。两个 SMTP_HOST 都启用过了。

```PHP
define('SITE_NAME', 'https://zhoucaiqi.com');
define('SMTP_SECURE', 'ssl');
define('SMTP_HOST', 'hwsmtp.exmail.qq.com');
// define('SMTP_HOST', 'smtp.exmail.qq.com');
define('SMTP_PORT', 465);
define('SMTP_USERNAME', '完整的email地址');
define('SMTP_PASSWORD', '已填写');
```

**Comment by fooleap** [comment]
@choicky 可能是因为你的服务器是  HTTPS，请求需要验证证书。
目前已设置禁止验证，获取最新的 `postcomment.php` 文件，现在应该行。

**Comment by choicky** [comment]
@fooleap 刚才更新了，匿名评论者目前依然没有收到邮件通知。

我记得 Ghost v1.x 版本时，是推荐使用 mailgun 之类的第三方来发邮件的，那时候邮件都是正常的。你有空也可以参考下 ：）

对了，同一个服务器上，我搭建了一个 wordpress ，印象中 wordpress 的邮件通知是正常的。所以可以参考有一下 wordpress 的代码？

**Comment by fooleap** [comment]
那现在可能要调试看看，`postcomment.php` 文件[第 62 行](https://github.com/fooleap/disqus-php-api/blob/master/api/postcomment.php#L62)中的 URL 换成绝对地址试试看。

之前为了方便就用 PHPMailer，Mailgun 没了解过，有时间看看，WP 好像是自带就有邮件模块。

**Comment by fooleap** [comment]
@choicky 刚刚用你的 `sendemail` 接口做测试，成功发送了回复邮件。
![](http://ww1.sinaimg.cn/large/699600a0gy1fh705hizl4j20f708cq42.jpg)

**Comment by choicky** [comment]
@fooleap 我看到你的“测试”评论了，我回复了你，你的QQ信箱有收到吗？
如果你没有收到，难道是我的 smtp 设置有问题？例如，不能启用 ssl，必须使用非 ssl 的smtp 设置？

**Comment by fooleap** [comment]
你的回复我没收到，反而我用 js 发请求收到了，感觉有可能是上面说的那个 url 的问题。

**Comment by choicky** [comment]
第62行的 url 改为绝对路径，是指 https:// 开头的，还是 服务器的存储地址（以/开头的）？

**Comment by fooleap** [comment]
https 开头的，就是网址。

**Comment by choicky** [comment]
改为了 `CURLOPT_URL => 'https://disqus-zhoucaiqi-com.fei-xing.com/api/sendemail.php',`

但目前依然收不到。不知道是咋回事了。
