### ISSUE TITLE
now.sh v2 不再支持docker部署，能否更新以兼容v2？

### ISSUE THREAD

**Issue by cubarco** [fooleap/disqus-php-api#45]
开发者你好，
今天在尝试适配now.sh的v2规则时，发现now.sh有一个build-sources的限制。在一次部署中，不允许超过32个资源文件（Free plan），请问能否精简php文件数；或者，若只需要简单的评论功能，能否指明哪些php是非必须的？
谢谢！

关于限制： https://zeit.co/docs/v2/deployments/builds/#build-sources-limit

**Comment by cubarco** [comment]
开发者你好，
今天在尝试适配now.sh的v2规则时，发现now.sh有一个build-sources的限制。在一次部署中，不允许超过32个资源文件（Free plan），请问能否精简php文件数；或者，若只需要简单的评论功能，能否指明哪些php是非必须的？
谢谢！

关于限制： https://zeit.co/docs/v2/deployments/builds/#build-sources-limit

**Comment by fooleap** [comment]
今日我有在尝试部署到 now，貌似 now v2 没有当前目录创建文件的权限。
而文件数的问题，我再修改下，合并某些文件。

**Comment by cubarco** [comment]
谢谢回复，
如果能尽可能减少php文件数，那就最好了。
