### ISSUE TITLE
无法正确在now.json部署

### ISSUE THREAD

**Issue by KaitoHH** [fooleap/disqus-php-api#46]
首先，如果我直接执行`now`命令，它会报下面这个错误
```
You defined 1 build that did not match any source files (please ensure they are NOT defined in .nowignore)
```
所以修改了`now.json`文件变成如下形式
```json
{
  "version": 2,
  "builds": [{ "src": "*/*.php", "use": "@now/php" }]
}
```
重新执行`now`是可以成功部署的，但是访问`<url>/api/login.php`时提示没有权限。

由于同样的配置文件，在我自己的主机上能正确部署，因此配置文件应当是没有问题的。我同样修改了disqus设置中对应的回调地址，但问题依旧。

**Comment by fooleap** [comment]
now.json 我改改，now.sh 貌似没有在目录下写文件的权限，目前需要将 `config.php` 文件的 `USE_TEMP` 定义为 `true`

**Comment by KaitoHH** [comment]
你好，使用了修改之后的`now.json`仍然有一些文件缺失，所以我又做了略微的修改
```json
"builds": [
    { "src": "api/*.php", "use": "@now/php" },
    { "src": "api/PHPMailer/*.php", "use": "@now/php" },
    { "src": "api/emojione/*.php", "use": "@now/php" },
    { "src": "api/emojione/src/*.php", "use": "@now/php" },
    { "src": "dist/*", "use": "@now/static" }
  ]
```
现在可以正确部署了。

此外，我还注意到使用`USE_TEMP`之后邮件提醒无法正确的收到，另外在写日志时没有正确的使用临时地址

https://github.com/fooleap/disqus-php-api/blob/ffc3fe11100ab9d4e2f4d1448c4ab0b2e6e673b3/api/sendemail.php#L192

在这行代码中仍然使用了`__DIR__`而非cache目录，这可能造成日志没有正确写入。

这只是我初步的发现，仅供参考，可能还存在其他的原因。
