### ISSUE TITLE
符号待完善

### ISSUE THREAD

**Issue by hubojing** [fooleap/disqus-php-api#5]
例如“*”、“#”一类，在PC端和移动(Android)端均无法显示，只能在disqus的反馈邮件中查看。影响体验，望改善，谢谢！

**Comment by fooleap** [comment]
请获取最新 PHP 代码即可，已有将此类常用符号排除在外。

**Comment by hubojing** [comment]
好的，请问更新代码是否会丢失现有的评论？

**Comment by fooleap** [comment]
不会的，并没有存储，评论数据都只在 Disqus 上。

**Comment by hubojing** [comment]
好的，非常感谢回复。
