### ISSUE TITLE
heroku上成功部署，也能加载demo，但是在hexo网站上一直显示“正在初始化”的动画

### ISSUE THREAD

**Issue by ajioy** [fooleap/disqus-php-api#51]
昨天好不容易成功在hexo网站(https://ajioy.cn/thinking/why-do-i-create-a-personal-website/) 上成功显示过一次disqus，因为有多余的thread，所以重新来过了，奇怪的是怎么做都没用了，尝试五六回都是如此，一直显示“正在初始化”，只好过来请教大神，如您空了还望帮忙看下是哪个环节出了问题。

前端部分disqusapi.pug
```javascript
if theme.disqusapi && theme.disqusapi.enable
  link(rel="stylesheet" href="https://cdn.jsdelivr.net/gh/ajioy/CDN/js/iDisqus.min.css")
  script(src='https://cdn.jsdelivr.net/gh/ajioy/CDN/js/iDisqus.min.js')
  #comment
  script.
    var disq = new iDisqus('comment', {
      forum: 'ajioy.cn',
      api: 'https://ajioycn.herokuapp.com/api/',
      site: 'https://ajioy.cn',
      mode: 1,
      timeout: 3000,
      init: true,
      emojiPreview: true
    });
    disq.count();
```
后端heroku demo(https://ajioycn.herokuapp.com/dist/)

**Comment by fooleap** [comment]
heroku 上部署的，在你博客上加载有跨域问题。
![跨域问题](https://uploads.disquscdn.com/images/e32225e5ccee0fe227383c42a3fa7aa74ac5e95b40dbc16391564ee96073649e.png )

**Comment by ajioy** [comment]
谢谢指点，问题已解决，将init.php中第25行header('Access-Control-Allow-Origin: '.$origin);更改成自己的域名即可。
