### ISSUE TITLE
有没有办法部署到阿里云的函数计算上

### ISSUE THREAD

**Issue by heiybb** [fooleap/disqus-php-api#53]
注意到阿里云的函数计算提供了PHP的HTTP Trigger环境
这样可以直接使用香港的区域来部署

我不是很会PHP 也有看到Node.JS的版本也不会= =
太难了

**Comment by fooleap** [comment]
试了一下，用来做跳板可行，只不过貌似无法存储数据，存临时目录很快被删，匿名评论等需要这方面的支持。

**Comment by heiybb** [comment]
奇怪
我尝试在自己主机上部署之后
init.php内修改了allow origin为*
依然有这样的错误
```
Access to XMLHttpRequest at 'https://api.heiybb.com/api/user.php' from origin 'https://heiybb.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by heiybb** [comment]
> 奇怪
> 我尝试在自己主机上部署之后
> init.php内修改了allow origin为*
> 依然有这样的错误
> 
> ```
> Access to XMLHttpRequest at 'https://api.heiybb.com/api/user.php' from origin 'https://heiybb.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> ```

关闭主题自带的PJAX然后设置为指定域名后解决了
