### ISSUE TITLE
评论不了

### ISSUE THREAD

**Issue by sengmitnick** [fooleap/disqus-php-api#6]
最近怎么评论不了了
![](https://uploads.disquscdn.com/images/07315bb15c54f151617bbe994e3018ad1c3532641686bae4d08dfa8dae10027b.png)
如图，评论后不是实体而且有点虚的感觉，按F5后评论就消失了.
做过测试，就是如果在网址一栏填写了没有http开头的网址就会这样子。

**Comment by fooleap** [comment]
发表评论请求的优化空间还很大，特别是错误提醒，此前简单的使用 `alert()`，现在都去掉了，等有空再加上其他形式的。

**Comment by fooleap** [comment]
访客信息已有进行必要的验证，没通过不发送请求。

**Comment by hubojing** [comment]
我是说怎么手机无法评论，原来是http://的锅…谢谢了。
