### ISSUE TITLE
建议：添加信息没写或者填写错误时进行提示

### ISSUE THREAD

**Issue by sengmitnick** [fooleap/disqus-php-api#7]
可以参照一下原disqus评论框:
![](https://uploads.disquscdn.com/images/007d7f5fa59d112a7a74739a9e2a42c26a6a26e2786bc69731f57352735a4d20.png)
![](https://uploads.disquscdn.com/images/f4b370bcb4403938602929f541c48ca725f6d69483ba69a4bd52839f51109a1c.png)

**Comment by fooleap** [comment]
收到，这个等有空弄弄。

**Comment by fooleap** [comment]
已简单添加大部分的提示，有需要再补充。
