### ISSUE TITLE
可考虑加上删除评论

### ISSUE THREAD

**Issue by hubojing** [fooleap/disqus-php-api#9]
删除评论只能通过disqus后台删除。能不能直接在评论“回复”后加上“删除”，也方便其他留言者。谢谢~

**Comment by fooleap** [comment]
1、如果没有登录态，直接显示删除按钮，感觉不够安全，若遇到恶搞的访问者，可能会把你评论删完去。
2、自己管理可以切换至 Disqus 评论框，或者前往右上角“Disqus 讨论区”，直接管理该页面的评论。
3、考虑在访客发表评论后增加编辑和删除按钮，刷新页面前可操作，后端限制评论发表的时间差，以策安全。

**Comment by hubojing** [comment]
好的，另外，更新后emoji表情反而用不了了。邮件设置也并未收到已回复邮件。不知道是否设置错误：服务器名称: smtp-mail.outlook.com
端口: 587
加密方法: STARTTLS

**Comment by fooleap** [comment]
@hubojing 之前有一次 push 存在 bug，表情用不了了，现在的不会。
邮件我刚用 outlook 去试，可以发送成功，端口等跟你一样。

**Comment by fooleap** [comment]
回复成功后已加上删除按钮，创建评论十分钟内可操作。

**Comment by hubojing** [comment]
删除后再想评论同样的话就不行了You have already made this comment.
不过意义也不太大  已经很好了  感谢感谢

**Comment by fooleap** [comment]
编辑评论已添加，不常规操作可能会有小错误

**Comment by hubojing** [comment]
好的，另外我觉得一个月以前的评论可以显示对应日期了，都是“一个月前”太笼统。只是个人观点。

**Comment by fooleap** [comment]
保持格式一致，这个就不改了。这样吧，还跟原生评论框一样加个 `title` 属性，值是具体时间。

**Comment by hubojing** [comment]
更新后评论怎么变成顺序的了，另外请教下title是在哪修改，并没用过php

**Comment by fooleap** [comment]
title 是改 js 的，你更新后变顺序可能因为php 或者 js 有一个没更新，又或者是 js浏览器有缓存。

**Comment by hubojing** [comment]
哦，另外图片始终正在加载无法上传成功，只能翻墙登disqus传图，不知道是不是个例。

**Comment by fooleap** [comment]
http://disqus.hubojing.me/upload.php我发现打不开
